export enum OpCode {
  LOG0 = 'LOG0',
  LOG1 = 'LOG1',
  LOG2 = 'LOG2',
  LOG3 = 'LOG3',
  LOG4 = 'LOG4',
  CALL = 'CALL',
  SELF_DESTRUCT_OP_CODE = 'SELFDESTRUCT',
  CREATE_OP_CODE_1 = 'CREATE',
  CREATE_OP_CODE_2 = 'CREATE2',
}
